Add support for v5 signatures
duosecurity/duo_api_golang pull request #48
Opened 2023-08-24 20:44 UTC by jaherne-duo

## Description
This PR adds a new function `JSONSignedCall()`. Calls made through this function will use a v5 signature automatically. 

## Motivation and Context
V5 signatures and params encoded as JSON are required for the new policy API endpoints (see https://duo.com/docs/adminapi#policies). However, updating the existing SignedCall function would break existing golang client users. By adding a separate call, we can add support for future policy calls without disrupting existing code.

## How Has This Been Tested?
Added new tests for the internal functions. Also verified the new call works with GETs and POSTs, both with and without params.

Example of how to use the new function:
```
func EnrollStatusV5(api *duoapi.DuoApi, userid string,
	activationCode string) (*authapi.EnrollStatusResult, error) {
	params := duoapi.JSONParams{
		"user_id":         userid,
		"activation_code": activationCode,
	}
	_, body, err := api.JSONSignedCall("POST", "/auth/v2/enroll_status", params)
	ret := &authapi.EnrollStatusResult{}
	if err = json.Unmarshal(body, ret); err != nil {
		return nil, err
	}
	return ret, nil
}
```

## Types of Changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-08-24 21:03 UTC, cisco-kyluce commented on duoapi.go
> +func (duoapi *DuoApi) JSONSignedCall(method string,
very nice, I feel like this strikes a good balance!

2023-08-25 17:20 UTC, seanpd-duo commented on duoapi.go
> +// method is POST or GET
method could also be a PUT

2023-08-25 17:46 UTC, jaherne-duo commented on duoapi.go
> +// method is POST or GET
Updated, thanks!

2023-09-07 17:30 UTC, mbish requested changes

2023-09-07 17:35 UTC, mbish commented on duoapi.go
> +		if err == nil {
Can you change this check to just check for an error and if there isn't one to proceed with the Encode call
```
if err != nil {
    return nil, nil, err
}
api_url.RawQuery = url_values.Encode()
```
I think it reads easier as a default case.

2024-02-02 19:17 UTC, mbish approved these changes

2024-02-05 14:40 UTC, merged